export const environment = {
    production: false,
    LOGOUT: 'https://accelerate-integration.hhs.gov/landing',
    UNITED_ENV: 'https://accelerate-integration.hhs.gov',
    DOMAIN_URL:'https://accelerate-integration.hhs.gov/acc-api/',
    NAICS:'https://accelerate-integration.hhs.gov/acc-api/naics',
    CLAUSE_DESC_URL: "https://accelerate-integration.hhs.gov/acc-api/ai-svc/clause/",
    SOW:'https://accelerate-integration.hhs.gov/acc-api/sow',
    IGCE:'https://accelerate-integration.hhs.gov/acc-api/igce',
    REQUISITION:'https://accelerate-integration.hhs.gov/acc-api/requisition',
    EVAL_CRITERIA:'https://accelerate-integration.hhs.gov/acc-api/evaluation-criteria',
    CORS:'https://accelerate-integration.hhs.gov/acc-api/cors/' ,
    ESTIMATES:'https://accelerate-integration.hhs.gov/acc-api/estimates',
    COMATIBILITIES:'https://accelerate-integration.hhs.gov/acc-api/compatibilities',
    COMPETETIONS:'https://accelerate-integration.hhs.gov/acc-api/competitions',
    CONSTRAINTS:'https://accelerate-integration.hhs.gov/acc-api/constraints',
    TRADEOFF:'https://accelerate-integration.hhs.gov/acc-api/tradeoffs',
    AI_SVC:'https://accelerate-integration.hhs.gov/acc-api/ai-svc',
    ATTACHMENT: 'https://accelerate-integration.hhs.gov/acc-api/attachment',
    PSC: 'https://accelerate-integration.hhs.gov/acc-api/psc',
    PROPOSAL_EVAL: 'https://accelerate-integration.hhs.gov/acc-api/proposal-eval',
    EVALUATOR: 'https://accelerate-integration.hhs.gov/acc-api/evaluator',
    VENDORQA: 'https://accelerate-integration.hhs.gov/acc-api/vendor-qa',
    AP_DAPP:'https://accelerate-integration.hhs.gov/acc-api/ap-dapp/',
    SOL_DAPP:'https://accelerate-integration.hhs.gov/acc-api/sol-dapp/',
    APS_URL: 'https://accelerate-integration.hhs.gov/acc-api/ap',
    SOL_URL: 'https://accelerate-integration.hhs.gov/acc-api/sol',
    FORMS_URL: 'https://accelerate-integration.hhs.gov/acc-api/form/',
    SECTIONS_URL: 'https://accelerate-integration.hhs.gov/acc-api/sections/',
    CONTRACT_DAPP:'https://accelerate-integration.hhs.gov/acc-api/contract-dapp/',
    CONTRACT:'https://accelerate-integration.hhs.gov/acc-api/contract/',
    SECTION508:'https://accelerate-integration.hhs.gov/acc-api/section508',
    SECURITY:'https://accelerate-integration.hhs.gov/acc-api/security' ,
    CONSIDERATION:'https://accelerate-integration.hhs.gov/acc-api/consideration',
    AI_FEEDBACK: 'https://accelerate-integration.hhs.gov/acc-api/feedback',
  };
  