
// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
    production: false,
    // LOGOUT: "https://idp.int.identitysandbox.gov/logout",
    // UNITED_ENV: 'https://staging.accelerate.hhs.gov',
    // DOMAIN_URL:'https://staging.accelerate.hhs.gov/acc-api/',
    // CLAUSE_DESC_URL: "https://staging.accelerate.hhs.gov/acc-api/ai-svc/clause/",
    // NAICS:'https://staging.accelerate.hhs.gov/acc-api/naics',
    // SOW:'https://staging.accelerate.hhs.gov/acc-api/sow',
    // IGCE:'https://staging.accelerate.hhs.gov/acc-api/igce',
    // REQUISITION:'https://staging.accelerate.hhs.gov/acc-api/requisition',
    // EVAL_CRITERIA:'https://staging.accelerate.hhs.gov/acc-api/evaluation-criteria',
    // ESTIMATES:'https://staging.accelerate.hhs.gov/acc-api/estimates',
    // COMATIBILITIES:'https://staging.accelerate.hhs.gov/acc-api/compatibilities',
    // COMPETETIONS:'https://staging.accelerate.hhs.gov/acc-api/competitions',
    // CONSTRAINTS:'https://staging.accelerate.hhs.gov/acc-api/constraints',
    // TRADEOFF:'https://staging.accelerate.hhs.gov/acc-api/tradeoffs',
    // AI_SVC:'https://staging.accelerate.hhs.gov/acc-api/ai-svc',
    // ATTACHMENT: 'https://staging.accelerate.hhs.gov/acc-api/attachment',
    // PSC: 'https://staging.accelerate.hhs.gov/acc-api/psc',
    // PROPOSAL_EVAL: 'https://staging.accelerate.hhs.gov/acc-api/proposal-eval',
    // EVALUATOR: 'https://staging.accelerate.hhs.gov/acc-api/evaluator',
    // VENDORQA: 'https://staging.accelerate.hhs.gov/acc-api/vendor-qa',
    // AP_DAPP:'https://staging.accelerate.hhs.gov/acc-api/ap-dapp/',
    // SOL_DAPP:'https://staging.accelerate.hhs.gov/acc-api/sol-dapp/',
    // APS_URL: 'https://staging.accelerate.hhs.gov/acc-api/ap',
    // SOL_URL: 'https://staging.accelerate.hhs.gov/acc-api/sol',
    // FORMS_URL: 'https://staging.accelerate.hhs.gov/acc-api/form/',
    // SECTIONS_URL: 'https://staging.accelerate.hhs.gov/acc-api/sections/',
    // CONTRACT_DAPP:'https://staging.accelerate.hhs.gov/acc-api/contract-dapp/',
    // CONTRACT:'https://staging.accelerate.hhs.gov/acc-api/contract/',
    // CORS:'https://staging.accelerate.hhs.gov/acc-api/cors/',
    // SECTION508:'https://staging.accelerate.hhs.gov/acc-api/section508',
    // SECURITY:'https://staging.accelerate.hhs.gov/acc-api/security' ,
    // CONSIDERATION:'https://staging.accelerate.hhs.gov/acc-api/consideration'



    LOGOUT: "https://idp.int.identitysandbox.gov/logout",
    UNITED_ENV: 'https://staging.accelerate.hhs.gov',
    DOMAIN_URL:'https://api-staging.accelerate.hhs.gov/acc-api/',
    CLAUSE_DESC_URL: "https://api-staging.accelerate.hhs.gov/acc-api/ai-svc/clause/",
    NAICS:'https://api-staging.accelerate.hhs.gov/acc-api/naics',
    SOW:'https://api-staging.accelerate.hhs.gov/acc-api/sow',
    IGCE:'https://api-staging.accelerate.hhs.gov/acc-api/igce',
    REQUISITION:'https://api-staging.accelerate.hhs.gov/acc-api/requisition',
    EVAL_CRITERIA:'https://api-staging.accelerate.hhs.gov/acc-api/evaluation-criteria',
    ESTIMATES:'https://api-staging.accelerate.hhs.gov/acc-api/estimates',
    COMATIBILITIES:'https://api-staging.accelerate.hhs.gov/acc-api/compatibilities',
    COMPETETIONS:'https://api-staging.accelerate.hhs.gov/acc-api/competitions',
    CONSTRAINTS:'https://api-staging.accelerate.hhs.gov/acc-api/constraints',
    TRADEOFF:'https://api-staging.accelerate.hhs.gov/acc-api/tradeoffs',
    AI_SVC:'https://api-staging.accelerate.hhs.gov/acc-api/ai-svc',
    ATTACHMENT: 'https://api-staging.accelerate.hhs.gov/acc-api/attachment',
    PSC: 'https://api-staging.accelerate.hhs.gov/acc-api/psc',
    PROPOSAL_EVAL: 'https://api-staging.accelerate.hhs.gov/acc-api/proposal-eval',
    EVALUATOR: 'https://api-staging.accelerate.hhs.gov/acc-api/evaluator',
    VENDORQA: 'https://api-staging.accelerate.hhs.gov/acc-api/vendor-qa',
    AP_DAPP:'https://api-staging.accelerate.hhs.gov/acc-api/ap-dapp/',
    SOL_DAPP:'https://api-staging.accelerate.hhs.gov/acc-api/sol-dapp/',
    APS_URL: 'https://api-staging.accelerate.hhs.gov/acc-api/ap',
    SOL_URL: 'https://api-staging.accelerate.hhs.gov/acc-api/sol',
    FORMS_URL: 'https://api-staging.accelerate.hhs.gov/acc-api/form/',
    SECTIONS_URL: 'https://api-staging.accelerate.hhs.gov/acc-api/sections/',
    CONTRACT_DAPP:'https://api-staging.accelerate.hhs.gov/acc-api/contract-dapp/',
    CONTRACT:'https://api-staging.accelerate.hhs.gov/acc-api/contract/',
    CORS:'https://api-staging.accelerate.hhs.gov/acc-api/cors/',
    SECTION508:'https://api-staging.accelerate.hhs.gov/acc-api/section508',
    SECURITY:'https://api-staging.accelerate.hhs.gov/acc-api/security' ,
    CONSIDERATION:'https://api-staging.accelerate.hhs.gov/acc-api/consideration',
    AI_FEEDBACK: 'https://api-staging.accelerate.hhs.gov/acc-api/feedback', 
  };
  