
// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  production: false,
  LOGOUT: 'https://integration.accelerate.hhs.gov/landing',
  UNITED_ENV: 'https://integration.accelerate.hhs.gov',
  DOMAIN_URL:'https://api-integration.accelerate.hhs.gov/acc-api/',
  NAICS:'https://api-integration.accelerate.hhs.gov/acc-api/naics',
  CLAUSE_DESC_URL: "https://api-integration.accelerate.hhs.gov/acc-api/ai-svc/clause/",
  SOW:'https://api-integration.accelerate.hhs.gov/acc-api/sow',
  IGCE:'https://api-integration.accelerate.hhs.gov/acc-api/igce',
  REQUISITION:'https://api-integration.accelerate.hhs.gov/acc-api/requisition',
  EVAL_CRITERIA:'https://api-integration.accelerate.hhs.gov/acc-api/evaluation-criteria',
  ESTIMATES:'https://api-integration.accelerate.hhs.gov/acc-api/estimates',
  COMATIBILITIES:'https://api-integration.accelerate.hhs.gov/acc-api/compatibilities',
  COMPETETIONS:'https://api-integration.accelerate.hhs.gov/acc-api/competitions',
  CONSTRAINTS:'https://api-integration.accelerate.hhs.gov/acc-api/constraints',
  TRADEOFF:'https://api-integration.accelerate.hhs.gov/acc-api/tradeoffs',
  AI_SVC:'https://api-integration.accelerate.hhs.gov/acc-api/ai-svc',
  ATTACHMENT: 'https://api-integration.accelerate.hhs.gov/acc-api/attachment',
  PSC: 'https://api-integration.accelerate.hhs.gov/acc-api/psc',
  PROPOSAL_EVAL: 'https://api-integration.accelerate.hhs.gov/acc-api/proposal-eval',
  EVALUATOR: 'https://api-integration.accelerate.hhs.gov/acc-api/evaluator',
  VENDORQA: 'https://api-integration.accelerate.hhs.gov/acc-api/vendor-qa',
  AP_DAPP:'https://api-integration.accelerate.hhs.gov/acc-api/ap-dapp/',
  SOL_DAPP:'https://api-integration.accelerate.hhs.gov/acc-api/sol-dapp/',
  APS_URL: 'https://api-integration.accelerate.hhs.gov/acc-api/ap',
  SOL_URL: 'https://api-integration.accelerate.hhs.gov/acc-api/sol',
  FORMS_URL: 'https://api-integration.accelerate.hhs.gov/acc-api/form/',
  SECTIONS_URL: 'https://api-integration.accelerate.hhs.gov/acc-api/sections/',
  CONTRACT_DAPP:'https://api-integration.accelerate.hhs.gov/acc-api/contract-dapp/',
  CONTRACT:'https://api-integration.accelerate.hhs.gov/acc-api/contract/',
  CORS:'https://api-integration.accelerate.hhs.gov/acc-api/cors/',
  SECTION508:'https://api-integration.accelerate.hhs.gov/acc-api/section508',
  SECURITY:'https://api-integration.accelerate.hhs.gov/acc-api/security' ,
  CONSIDERATION:'https://api-integration.accelerate.hhs.gov/acc-api/consideration',
  AI_FEEDBACK: 'https://api-integration.accelerate.hhs.gov/acc-api/feedback', 

  // LOGOUT: 'https://integration.accelerate.hhs.gov/landing',
  // UNITED_ENV: 'https://integration.accelerate.hhs.gov',
  // DOMAIN_URL:'https://integration.accelerate.hhs.gov/acc-api/',
  // CLAUSE_DESC_URL:"https://service.accelerate-dev.com/acc-api/ai-svc/clause/",
  // NAICS:'https://integration.accelerate.hhs.gov/acc-api/naics',
  // SOW:'https://integration.accelerate.hhs.gov/acc-api/sow',
  // IGCE:'https://integration.accelerate.hhs.gov/acc-api/igce',
  // REQUISITION:'https://integration.accelerate.hhs.gov/acc-api/requisition',
  // EVAL_CRITERIA:'https://integration.accelerate.hhs.gov/acc-api/evaluation-criteria',
  // ESTIMATES:'https://integration.accelerate.hhs.gov/acc-api/estimates',
  // COMATIBILITIES:'https://integration.accelerate.hhs.gov/acc-api/compatibilities',
  // COMPETETIONS:'https://integration.accelerate.hhs.gov/acc-api/competitions',
  // CONSTRAINTS:'https://integration.accelerate.hhs.gov/acc-api/constraints',
  // TRADEOFF:'https://integration.accelerate.hhs.gov/acc-api/tradeoffs',
  // AI_SVC:'https://integration.accelerate.hhs.gov/acc-api/ai-svc',
  // ATTACHMENT: 'https://integration.accelerate.hhs.gov/acc-api/attachment',
  // PSC: 'https://integration.accelerate.hhs.gov/acc-api/psc',
  // PROPOSAL_EVAL: 'https://integration.accelerate.hhs.gov/acc-api/proposal-eval',
  // EVALUATOR: 'https://integration.accelerate.hhs.gov/acc-api/evaluator',
  // VENDORQA: 'https://integration.accelerate.hhs.gov/acc-api/vendor-qa',
  // AP_DAPP:'https://integration.accelerate.hhs.gov/acc-api/ap-dapp/',
  // SOL_DAPP:'https://integration.accelerate.hhs.gov/acc-api/sol-dapp/',
  // APS_URL: 'https://integration.accelerate.hhs.gov/acc-api/ap',
  // SOL_URL: 'https://integration.accelerate.hhs.gov/acc-api/sol',
  // FORMS_URL: 'https://integration.accelerate.hhs.gov/acc-api/form/',
  // SECTIONS_URL: 'https://integration.accelerate.hhs.gov/acc-api/sections/',
  // CONTRACT_DAPP:'https://integration.accelerate.hhs.gov/acc-api/contract-dapp/',
  // CONTRACT:'https://integration.accelerate.hhs.gov/acc-api/contract/',
  // CORS:'https://integration.accelerate.hhs.gov/acc-api/cors/',
  // SECTION508:'http://www.accelerate-demo.com/acc-api/section508',
  // SECURITY:'http://www.accelerate-demo.com/acc-api/security' ,
  // CONSIDERATION:'http://www.accelerate-demo.com/acc-api/consideration'

};
